# Instead of using TAB for indentation, use two spaces at the place of one TAB

# Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_1, joint_2, joint_3, joint_4, joint_5]
  
# Controller to control end effector joints
hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [ee_thumb_prox_joint, ee_thumb_dist_joint, ee_finger1_roll_joint, ee_finger1_prox_joint, ee_finger1_dist_joint, ee_finger2_roll_joint, ee_finger2_prox_joint, ee_finger2_dist_joint]

# Controller to continuously publish joint states/positions. Rate is in Hz.
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
